# -*- coding: utf-8 -*-
"""Neural Style Transfer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IjrYhLmOoh-5dBg6NoOhj7OPqBq1hlh
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tensorflow
import tensorflow_hub as hub
import numpy as np
import PIL.Image
import time
import functools
import os

# --- 1. Konfigurasi dan Fungsi Utilitas ---

def tensor_to_image(tensor):
  """Mengubah tensor TensorFlow kembali menjadi gambar standar."""
  tensor = tensor*255
  tensor = np.array(tensor, dtype=np.uint8)
  if np.ndim(tensor)>3:
    assert tensor.shape[0] == 1
    tensor = tensor[0]
  return PIL.Image.fromarray(tensor)

def load_img(path_to_img):
  """Memuat gambar dan mengubah ukurannya agar kompatibel dengan model."""
  max_dim = 512
  img = tensorflow.io.read_file(path_to_img)
  img = tensorflow.image.decode_image(img, channels=3)
  img = tensorflow.image.convert_image_dtype(img, tensorflow.float32)

  shape = tensorflow.cast(tensorflow.shape(img)[:-1], tensorflow.float32)
  long_dim = max(shape)
  scale = max_dim / long_dim

  new_shape = tensorflow.cast(shape * scale, tensorflow.int32)

  img = tensorflow.image.resize(img, new_shape)
  img = img[tensorflow.newaxis, :]
  return img

# --- 2. Memuat Gambar (Pastikan Anda sudah upload gambar ke Colab) ---
#  - Contoh konsep gambar Style
#  - Contoh konsep gambar Content

print("Memuat gambar...")

# Cek apakah file ada, jika tidak gunakan gambar dummy dari internet untuk demo
content_path = '/content/drive/MyDrive/datasets/singa.jpg'
style_path = '/content/drive/MyDrive/datasets/Lukisan Cat Air.jpg'

if not os.path.exists(content_path) or not os.path.exists(style_path):
    print("File 'content.jpg' atau 'style.jpg' tidak ditemukan.")
    print("Mengunduh gambar sampel dari internet untuk demonstrasi...")

    # Download sampel jika user belum upload
    content_path = tensorflow.keras.utils.get_file('content.jpg', 'https://storage.googleapis.com/download.tensorflow.org/example_images/YellowLabradorLooking_new.jpg')
    style_path = tensorflow.keras.utils.get_file('style.jpg', 'https://storage.googleapis.com/download.tensorflow.org/example_images/Vassily_Kandinsky_-_Composition_7.jpg')

content_image = load_img(content_path)
style_image = load_img(style_path)

print("Gambar berhasil dimuat!")

# --- 3. Memuat Model Neural Style Transfer ---
# Kita menggunakan model pre-trained dari TensorFlow Hub untuk hasil cepat dan artistik
print("Sedang memuat model Neural Style Transfer dari TensorFlow Hub...")
hub_model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')
print("Model berhasil dimuat.")

# --- 4. Proses Style Transfer ---
print("Sedang memproses kombinasi gambar (ini mungkin memakan waktu beberapa detik)...")
start_time = time.time()

# Ini adalah inti dari proses: Menerapkan style ke content image
stylized_image = hub_model(tensorflow.constant(content_image), tensorflow.constant(style_image))[0]

end_time = time.time()
print(f"Selesai dalam {end_time - start_time:.2f} detik.")

# --- 5. Menyimpan Hasil ---
output_filename = 'hasil_kombinasi.jpg'
final_image = tensor_to_image(stylized_image)
final_image.save(output_filename)

print(f"Gambar hasil kombinasi telah disimpan sebagai: {output_filename}")
print("Silakan unduh gambar tersebut dari panel file di sebelah kiri.")